name: Build and Push DevContainer Image

on:
  workflow_dispatch:

  push:
    branches: [main]
    paths:
      - ".devcontainer/**"
      - ".github/workflows/devcontainer.yml"
      - "Dockerfile"

jobs:
  build-push:
    name: Build and Push DevContainer
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .devcontainer/Dockerfile
          push: true
          tags: ghcr.io/shuttle-hq/shuttle-shellcon-devcontainer:latest
